apiVersion: v1
kind: Pod
metadata: 
  name: nginx-probe2
spec: 
  containers:
    - name: nginx
      image: nginx
      ports: 
        - containerPort: 80
      livenessProbe:
        httpGet:
          path: /healt
          port: 80
        initialDelaySeconds: 5
        periodSeconds: 5
        timeoutSeconds: 1
        successThreshold: 1
        failureThreshold: 3
      readinessProbe:
        tcpSocket:
          port: 8080
        initialDelaySeconds: 5
        periodSeconds: 10
