apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    apps: qlas
spec:
  replicas: 3
  selector:
    matchLabels:
      apps: qlas
  template:
    metadata:
      labels:
        apps: qlas
    spec:
      containers:
      - name: backend
        image: hisbu/nodeapp
        env:
          - name: NQ_DB_HOST
            value: db-service
          - name: NQ_DB_USER
            value: root
          - name: NQ_DB_PASSWORD
            value: password
          - name: NQ_DB_NAME
            value: dbqlas
        ports:
        - containerPort: 2017
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: NodePort
  selector:
    apps: qlas
  ports:
    - port: 2017
      targetPort: 2017
      nodePort: 32003