apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  labels:
    app: database
    apps: qlas
spec:
  replicas: 3
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
        apps: qlas
    spec:
      containers:
      - name: dbserver
        image: mariadb:10.3
        ports:
        - containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: password
          - name: MYSQL_DATABASE
            value: dbqlas

---

apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  type: NodePort
  selector:
    app: database
    apps: qlas
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 32002